# Generated by Django 5.1.7 on 2026-06-11 22:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_matiere', models.CharField(max_length=20, unique=True, verbose_name='Code matière')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10)], verbose_name='Coefficient')),
                ('volume_horaire', models.PositiveIntegerField(verbose_name='Volume horaire (heures)')),
                ('niveau', models.CharField(choices=[('1ere', '1ère année'), ('2eme', '2ème année'), ('3eme', '3ème année'), ('4eme', '4ème année'), ('5eme', '5ème année')], max_length=10, verbose_name='Niveau')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('specialite', models.CharField(max_length=150, verbose_name='Spécialité')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9, verbose_name='Année scolaire')),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], verbose_name='Semestre')),
                ('date_affectation', models.DateField(verbose_name="Date d'affectation")),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='subjects.matiere', verbose_name='Matière')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='subjects.professeur', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['-annee_scolaire', 'semestre', 'matiere'],
                'constraints': [models.UniqueConstraint(fields=('professeur', 'matiere', 'annee_scolaire', 'semestre'), name='unique_affectation')],
            },
        ),
    ]
