# Generated by merging crm-python into CRMPROJECT on 2026-06-10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0005_niveau_parcours_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('filiere', models.CharField(choices=[('Marketing Digital', 'Marketing Digital et Data Analytics'), ('Commerce International', 'Commerce International'), ('Management', 'Management Global')], default='Marketing Digital', max_length=100)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100)),
                ('valeur', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='siteweb.etudiant')),
            ],
            options={
                'ordering': ['etudiant__nom', 'matiere'],
                'unique_together': {('etudiant', 'matiere')},
            },
        ),
    ]
