# Generated by Django 6.0.6 on 2026-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('midterm', 'Examen Mi-Semestre'), ('final', 'Examen Final'), ('quiz', 'Quiz'), ('assignment', 'Devoir'), ('other', 'Autre')], default='final', max_length=20),
        ),
    ]
